[
    "LA 1 [1080][Multiaudio]",
    "LA 1 UHD [1080][Multiaudio]",
    "LA 2",
    "TDP [TeleDeporte] [1080p]",
    "GOL TV [1080]",
    "CUATRO TV",
    "TeleCinco",
    "BE MAD [1080]",
    "MOVISTAR PLUS (FHD)(Elcano)",
    "MOVISTAR PLUS (FHD)(Elcano)",
    "BARCA TV [720]",
    "ESPORT 3 CAT [1080]",
    "REAL MADRID TV [1080]",
    "REAL MADRID TV [1080]",
    "REAL MADRID TV [1080]",
    "M LaLiga (NewLoop)",
    "M LaLiga (Elcano)",
    "M LaLiga (FHD)(Elcano)",
    "M LaLiga (FHD)(Elcano)",
    "M LaLiga (SD)(Elcano)",
    "M LaLiga 2 (FHD)(Elcano)",
    "M LaLiga 2 (SD)(Elcano)",
    "M LaLiga 3 (FHD)(Elcano)",
    "M LaLiga 3 (SD)(Elcano)",
    "M LaLiga 4 (FHD)(Elcano)",
    "M LaLiga 5 (FHD)(Elcano)",
    "M LaLiga 6 (FHD)(Elcano)",
    "M LaLiga 7 (FHD)(Elcano)",
    "LaLiga Tv Bar (FHD)(Elcano)",
    "LaLiga Tv Bar (FHD)(Elcano)",
    "DAZN LaLiga (FHD)(Elcano)",
    "DAZN LaLiga (FHD)(Elcano)",
    "DAZN LaLiga (FHD)(Elcano)",
    "DAZN LaLiga (SD)(Elcano)",
    "DAZN LaLiga 2 (FHD)(Elcano)",
    "DAZN LaLiga 2 (SD)(Elcano)",
    "DAZN LaLiga 3 (FHD)(Elcano)",
    "DAZN LaLiga 4 (FHD)(Elcano)",
    "DAZN LaLiga 5 (FHD)(Elcano)",
    "DAZN LaLiga 6 (FHD)(Elcano)",
    "LaLiga HyperMotion [1080]",
    "LaLiga HyperMotion [720]",
    "LaLiga HyperMotion 2 [1080]",
    "LaLiga HyperMotion 2 [720]",
    "LaLiga HyperMotion 3",
    "LaLiga HyperMotion 4",
    "LaLiga HyperMotion 5",
    "LaLiga HyperMotion 6",
    "LaLiga HyperMotion 7",
    "LaLiga HyperMotion 8",
    "LaLiga HyperMotion 9",
    "LaLiga HyperMotion 10",
    "COPA DEL REY 1 (1080)",
    "COPA DEL REY 2 (1080)",
    "COPA DEL REY (720)",
    "M. Liga de Campeones 1 (4 K)(NewEra)",
    "M. Liga de Campeones 1 (FHD)(NewEra)",
    "M. Liga de Campeones 1 (FHD)(NewEra)",
    "M. Liga de Campeones 1 (FHD)(NewEra)",
    "M. Liga de Campeones 1 (FHD)(NewEra)",
    "M. Liga de Campeones 1 (FHD)(NewEra)",
    "M. Liga de Campeones 1 (FHD)(NewEra)",
    "M. Liga de Campeones 1 (FHD)(NewEra)",
    "M. Liga de Campeones 2",
    "M. Liga de Campeones 2 (FHD)(NewEra)",
    "M. Liga de Campeones 2 (FHD)(NewEra)",
    "M. Liga de Campeones 2 (FHD)(NewEra)",
    "M. Liga de Campeones 2 (FHD)(NewEra)",
    "M. Liga de Campeones 3 (FHD)(NewEra)",
    "M. Liga de Campeones 3 (FHD)(NewEra)",
    "M. Liga de Campeones 3 (FHD)(NewEra)",
    "M. Liga de Campeones 4 (FHD)(NewEra)",
    "M. Liga de Campeones 4 (FHD)(NewEra)",
    "M. Liga de Campeones 4 (SD)(NewEra)",
    "M. Liga de Campeones 5 (FHD)(NewEra)",
    "M. Liga de Campeones 5 (FHD)(NewEra)",
    "M. Liga de Campeones 6 (FHD)(NewEra)",
    "M. Liga de Campeones 7 (FHD)(NewEra)",
    "M. Liga de Campeones 8 (FHD)(NewEra)",
    "M Deportes [1080]",
    "M Deportes [1080]",
    "M Deportes [720]",
    "M Deportes 2 [1080]",
    "M Deportes 3 [1080]",
    "M Deportes 4 [1080]",
    "M Deportes 5 [1080]",
    "M Deportes 6 [1080]",
    "M Deportes 7 [1080]",
    "DAZN 1 (FHD)(NewEra)",
    "DAZN 1 (FHD)(NewEra)",
    "DAZN 1 (FHD)(NewEra)",
    "DAZN 1 (FHD)(NewEra)",
    "DAZN 1 (SD)(ElCano)",
    "DAZN 2 (FHD)(NewEra)",
    "DAZN 2 (FHD)(ElCano)",
    "DAZN 2 (SD)(ElCano)",
    "DAZN 3 [1080]",
    "DAZN 4 [1080]",
    "DAZN F1 [1080]",
    "DAZN F1 [1080]",
    "DAZN F1 [1080]",
    "DAZN F1 [720]",
    "Tennis Channel",
    "M GOLF 1 [1080]",
    "M GOLF 1 [1080]",
    "M GOLF 2 [1080]",
    "EuroSport [4k]",
    "EuroSport",
    "EuroSport",
    "EuroSport 2 [1080]",
    "EuroSport 2 [1080]",
    "EuroSport 2 [1080]",
    "EuroSport 2 [1080]",
    "EuroSport 2 [1080]",
    "M #Vamos (FHD)(NewEra)",
    "M #Vamos (FHD)(NewEra)",
    "M #Vamos (FHD)(NewEra)",
    "M #Vamos (FHD)(Elcano)",
    "M #Vamos (FHD)(Elcano)",
    "Sport Tv 1 [1080p]",
    "Sport Tv 2 [1080p]",
    "Sport Tv 3 [1080p]",
    "PPVP 1",
    "PPVP 2",
    "PPVP 3",
    "PPVP 4",
    "ESPN Argentina [1080]",
    "ESPN 3 Argentina [1080]",
    "ESPN Uruguay [1080]",
    "ESPN 2 Uruguay [1080]",
    "ESPN 3 Uruguay [1080]",
    "ESPN Extra Uruguay [1080]",
    "ESPN DEPORTES",
    "ESPN HD [US]",
    "ESPN 2 [BE]",
    "ESPN Colombia",
    "ESPN 2 Colombia",
    "ESPN 3 Colombia",
    "ESPN Extra Colombia",
    "BT Sport1 (UK) [1080]",
    "BT Sport1 (UK) [1080]",
    "BT Sport2 (UK [1080])",
    "BT Sport3 (UK) [1080]",
    "BT Sport4 (UK) [1080]",
    "BT Sport5 (UK) [1080]",
    "BT Sport6 (UK) [1080]",
    "Sky Sport F1 [1080]",
    "Sky Sport F1",
    "Sky Sport F1",
    "Sky Sport Football (UK)",
    "Sky Sport Main Event (UK)",
    "ViaPlay Sports 1",
    "ViaPlay Sports 2",
    "beIN SPORTS 1 [FR]",
    "beIN SPORTS 2 [FR]",
    "beIN SPORTS 1  [BE]",
    "beIN SPORTS 2  [BE]",
    "beIN SPORTS 3  [BE]",
    "beIN SPORTS Ñ",
    "beIN SPORTS XtraÑ",
    "Eleven Sport 1 (BE)",
    "Eleven Sport 2 (PL)",
    "Eleven Sport 3 (PL)",
    "Eleven Sport 4 (PL)",
    "Extreme Sports 1",
    "Extreme Sports 2",
    "Extreme Sports 3 (PL)",
    "Eurosport 360 HD 1 [DE]",
    "Eurosport 360 HD 2 [DE]",
    "Eurosport 360 HD 3 [DE]",
    "Eurosport 360 HD 4 [DE]",
    "Eurosport 360 HD 5 [DE]",
    "Eurosport 360 HD 6 [DE]",
    "Eurosport 360 HD 7 [DE]",
    "Eurosport 360 HD 8 [DE]",
    "Eurosport 360 HD 9 [DE]",
    "Red Bull",
    "Red Bull TV",
    "Red Bull TV HD",
    "Red Bull TV UHD",
    "RED BULL TV (2+)",
    "UFC",
    "UFC",
    "UFC",
    "UFC",
    "Nba Tv (US)"
]